### ISSUE TITLE
Why ExpressDecoratedRouter.reset can't be called implicitly inside applyRoutes since this is best practices?

### ISSUE THREAD

**Issue by cchitsiang** [Alorel/express-decorated-router#19]
Hi,

Haven't start using it yet. but while reading the README.md, I noticed that it mentioned should call ExpressDecoratedRouter.reset after applyRoutes as best practices?

If this is best practices, imo it will be nice it called inside applyRoutes  to free up resources? Or any reason not doing this way.

Just curious, and my two cent.

**Comment by Alorel** [comment]
Because I want to give users the freedom to free up resources exactly when they choose to do so. Additionally, this way you can, for example, apply some part of your routes to several Express routers if you wish to, then load the rest and apply those to another express router.

**Comment by cchitsiang** [comment]
Ok, make sense!
