### ISSUE TITLE
PUT method was not exported

### ISSUE THREAD

**Issue by rremy** [Alorel/express-decorated-router#20]
Hello!

The PUT method was not exported in the index.ts.
I think you exported the PATCH method twice insted of PUT.

https://github.com/Alorel/express-decorated-router/blob/9418fe3bdbe2a3357cd6fe5c80b8282a2958938b/src/index.ts#L19

**Comment by Alorel** [comment]
Ah, good spot! I'll push a fix in a sec :)

**Comment by Alorel** [comment]
Should be fixed in 1.0.4
